export const RICHMOND_COMMERCIAL_PROOF = [
  {
    id: 'richmond-proof-1',
    title: 'QSR Lot Rebuild - South Richmond Corridor',
    description: 'Full mill-and-overlay with striping refresh and drainage correction for high-turnover traffic.',
    image_url: '/work/imported/KFC/IMG_9496.JPG',
    location: 'Richmond, VA',
    sqft: 36000,
    year: 2025,
    category: 'commercial',
  },
  {
    id: 'richmond-proof-2',
    title: 'Retail Parking Lot Rehab - Midlothian Turnpike',
    description: 'Crack routing, sealcoat prep, and phased paving to keep tenant access open.',
    image_url: '/work/imported/KFC/IMG_9514.JPG',
    location: 'Richmond, VA',
    sqft: 29000,
    year: 2024,
    category: 'commercial',
  },
  {
    id: 'richmond-proof-3',
    title: 'Drive-Thru Stack Lane Reconstruction - Northside',
    description: 'Heavy-duty section rebuild for braking zones and turning stress at peak hours.',
    image_url: '/work/imported/KFC/IMG_9512.JPG',
    location: 'Richmond, VA',
    sqft: 8200,
    year: 2024,
    category: 'commercial',
  },
  {
    id: 'richmond-proof-4',
    title: 'Commercial Access Lane Paving - Mechanicsville Route',
    description: 'Lane resurfacing with edge reinforcement and patch replacement in failure zones.',
    image_url: '/work/imported/KFC/IMG_9518.JPG',
    location: 'Richmond Metro, VA',
    sqft: 17000,
    year: 2023,
    category: 'commercial',
  },
  {
    id: 'richmond-proof-5',
    title: 'Restaurant Lot Overlay - Chesterfield County',
    description: 'Night-shift overlay and striping for minimal operating disruption.',
    image_url: '/work/imported/KFC/IMG_9518.JPG',
    location: 'Chesterfield, VA',
    sqft: 24500,
    year: 2023,
    category: 'commercial',
  },
  {
    id: 'richmond-proof-6',
    title: 'High-Traffic Lot Repair Program - West End',
    description: 'Multi-phase infrared repairs and patching before final surface treatment.',
    image_url: '/work/imported/KFC/IMG_9510.JPG',
    location: 'Richmond, VA',
    sqft: 21000,
    year: 2022,
    category: 'commercial',
  },
  {
    id: 'richmond-proof-7',
    title: 'Commercial Pavement Upgrade - Downtown Perimeter',
    description: 'Surface course replacement with updated ADA striping and stall layout.',
    image_url: '/work/imported/KFC/IMG_9500.JPG',
    location: 'Richmond, VA',
    sqft: 31200,
    year: 2022,
    category: 'commercial',
  },
  {
    id: 'richmond-proof-8',
    title: 'Medical Office Lot Resurface - Henrico',
    description: 'Phased rehab plan to keep patient and emergency access available all day.',
    image_url: '/work/imported/KFC/IMG_9514.JPG',
    location: 'Henrico, VA',
    sqft: 18800,
    year: 2021,
    category: 'commercial',
  },
  {
    id: 'richmond-proof-9',
    title: 'Warehouse Apron and Parking Expansion - I-95 Corridor',
    description: 'Apron strengthening and parking expansion for light-industrial circulation.',
    image_url: '/work/imported/KFC/IMG_9519.JPG',
    location: 'Richmond Metro, VA',
    sqft: 40200,
    year: 2021,
    category: 'industrial',
  },
  {
    id: 'richmond-proof-10',
    title: 'Shopping Center Lot Restoration - Southside',
    description: 'Targeted base repair, resurfacing, and line striping for retail turnover flow.',
    image_url: '/work/imported/va cars photos and videos for website/IMG_8729.JPG',
    location: 'Richmond, VA',
    sqft: 33500,
    year: 2020,
    category: 'commercial',
  },
]
