"""initial_schema

Revision ID: 0e263db2f322
Revises: bc2d5f75bee4
Create Date: 2026-04-30 22:22:30.634840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e263db2f322'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=60), nullable=False),
    sa.Column('input_pattern', sa.String(length=500), nullable=False),
    sa.Column('corrected_answer', sa.Text(), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_corrections_decision_type'), 'ai_corrections', ['decision_type'], unique=False)
    op.create_index(op.f('ix_ai_corrections_id'), 'ai_corrections', ['id'], unique=False)
    op.create_index(op.f('ix_ai_corrections_tenant_id'), 'ai_corrections', ['tenant_id'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('meta_title', sa.String(length=300), nullable=True),
    sa.Column('meta_description', sa.String(length=320), nullable=True),
    sa.Column('focus_keyword', sa.String(length=120), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('featured', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('read_time_minutes', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_blog_posts_slug')
    )
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=False)
    op.create_index(op.f('ix_blog_posts_tenant_id'), 'blog_posts', ['tenant_id'], unique=False)
    op.create_table('cashflow_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold_amount', sa.Float(), nullable=False),
    sa.Column('alert_email', sa.String(length=254), nullable=False),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashflow_alerts_id'), 'cashflow_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_cashflow_alerts_tenant_id'), 'cashflow_alerts', ['tenant_id'], unique=False)
    op.create_table('cashflow_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashflow_entries_id'), 'cashflow_entries', ['id'], unique=False)
    op.create_index(op.f('ix_cashflow_entries_tenant_id'), 'cashflow_entries', ['tenant_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('messages_json', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=True),
    sa.Column('customer_email', sa.String(length=254), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('last_service', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.create_index(op.f('ix_contact_messages_tenant_id'), 'contact_messages', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('customer_type', sa.String(length=30), nullable=True),
    sa.Column('is_franchise', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('last_job_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_state_code'), 'customers', ['state_code'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_recipient_email'), 'email_logs', ['recipient_email'], unique=False)
    op.create_table('follow_up_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_tasks_id'), 'follow_up_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_lead_id'), 'follow_up_tasks', ['lead_id'], unique=False)
    op.create_table('gallery_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('job_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('data_uri', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_images_id'), 'gallery_images', ['id'], unique=False)
    op.create_table('grade_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=60), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('input_summary', sa.String(length=500), nullable=True),
    sa.Column('ai_engine', sa.String(length=60), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('was_corrected', sa.Integer(), nullable=False),
    sa.Column('correction_applied', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_logs_decision_type'), 'grade_logs', ['decision_type'], unique=False)
    op.create_index(op.f('ix_grade_logs_id'), 'grade_logs', ['id'], unique=False)
    op.create_index(op.f('ix_grade_logs_tenant_id'), 'grade_logs', ['tenant_id'], unique=False)
    op.create_table('ground_scan_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_site_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('scan_area_sqft', sa.Float(), nullable=True),
    sa.Column('ticket_811', sa.String(length=100), nullable=True),
    sa.Column('ticket_status', sa.String(length=40), nullable=True),
    sa.Column('technologies_json', sa.Text(), nullable=True),
    sa.Column('utilities_json', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ground_scan_reports_id'), 'ground_scan_reports', ['id'], unique=False)
    op.create_index(op.f('ix_ground_scan_reports_project_site_id'), 'ground_scan_reports', ['project_site_id'], unique=False)
    op.create_index(op.f('ix_ground_scan_reports_tenant_id'), 'ground_scan_reports', ['tenant_id'], unique=False)
    op.create_table('human_review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=60), nullable=False),
    sa.Column('input_summary', sa.String(length=500), nullable=False),
    sa.Column('ai_answer', sa.Text(), nullable=False),
    sa.Column('ai_engine', sa.String(length=60), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_review_queue_id'), 'human_review_queue', ['id'], unique=False)
    op.create_index(op.f('ix_human_review_queue_tenant_id'), 'human_review_queue', ['tenant_id'], unique=False)
    op.create_table('innovations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=200), nullable=False),
    sa.Column('job_site', sa.String(length=300), nullable=True),
    sa.Column('date_tested', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_to_test', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_innovations_id'), 'innovations', ['id'], unique=False)
    op.create_index(op.f('ix_innovations_tenant_id'), 'innovations', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('service_type', sa.String(length=60), nullable=False),
    sa.Column('property_type', sa.String(length=30), nullable=False),
    sa.Column('urgency', sa.String(length=30), nullable=False),
    sa.Column('project_size_sqft', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('score_value', sa.Integer(), nullable=True),
    sa.Column('score_label', sa.String(length=10), nullable=True),
    sa.Column('score_priority', sa.Integer(), nullable=True),
    sa.Column('pipeline_stage', sa.String(length=30), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposal_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_reason', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('lien_calendar_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('project_address', sa.String(length=300), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('project_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_furnishing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preliminary_notice_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lien_filing_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('foreclosure_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lien_calendar_entries_id'), 'lien_calendar_entries', ['id'], unique=False)
    op.create_index(op.f('ix_lien_calendar_entries_state_code'), 'lien_calendar_entries', ['state_code'], unique=False)
    op.create_index(op.f('ix_lien_calendar_entries_tenant_id'), 'lien_calendar_entries', ['tenant_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_url', sa.String(length=1000), nullable=False),
    sa.Column('storage_provider', sa.String(length=60), nullable=True),
    sa.Column('linked_to_type', sa.String(length=60), nullable=True),
    sa.Column('linked_to_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_id'), 'media_files', ['id'], unique=False)
    op.create_index(op.f('ix_media_files_tenant_id'), 'media_files', ['tenant_id'], unique=False)
    op.create_table('page_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_page_contents_key')
    )
    op.create_index(op.f('ix_page_contents_id'), 'page_contents', ['id'], unique=False)
    op.create_index(op.f('ix_page_contents_key'), 'page_contents', ['key'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=200), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_lead_id'), 'payment_transactions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_stripe_checkout_session_id'), 'payment_transactions', ['stripe_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_tenant_id'), 'payment_transactions', ['tenant_id'], unique=False)
    op.create_table('permit_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('permit_number', sa.String(length=100), nullable=True),
    sa.Column('permit_type', sa.String(length=100), nullable=False),
    sa.Column('permit_status', sa.String(length=50), nullable=True),
    sa.Column('contractor_name', sa.String(length=200), nullable=True),
    sa.Column('contractor_license', sa.String(length=100), nullable=True),
    sa.Column('property_address', sa.String(length=300), nullable=False),
    sa.Column('property_city', sa.String(length=100), nullable=True),
    sa.Column('property_state', sa.String(length=2), nullable=True),
    sa.Column('property_zip', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('project_value', sa.Float(), nullable=True),
    sa.Column('estimated_sqft', sa.Float(), nullable=True),
    sa.Column('permit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('priority_label', sa.String(length=10), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permit_leads_id'), 'permit_leads', ['id'], unique=False)
    op.create_index(op.f('ix_permit_leads_permit_number'), 'permit_leads', ['permit_number'], unique=False)
    op.create_table('project_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('scheduled_days', sa.Integer(), nullable=True),
    sa.Column('actual_days', sa.Integer(), nullable=True),
    sa.Column('client_nps', sa.Integer(), nullable=True),
    sa.Column('punch_list_items', sa.Integer(), nullable=False),
    sa.Column('punch_list_closed', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_metrics_id'), 'project_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_project_metrics_lead_id'), 'project_metrics', ['lead_id'], unique=False)
    op.create_index(op.f('ix_project_metrics_tenant_id'), 'project_metrics', ['tenant_id'], unique=False)
    op.create_table('project_retrospectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.String(length=60), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_variance_days', sa.Integer(), nullable=True),
    sa.Column('cost_variance_pct', sa.Float(), nullable=True),
    sa.Column('supply_chain_issues', sa.Text(), nullable=True),
    sa.Column('soil_conditions', sa.Text(), nullable=True),
    sa.Column('design_conflicts', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_retrospectives_id'), 'project_retrospectives', ['id'], unique=False)
    op.create_index(op.f('ix_project_retrospectives_tenant_id'), 'project_retrospectives', ['tenant_id'], unique=False)
    op.create_table('project_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('service_type', sa.String(length=60), nullable=True),
    sa.Column('project_size_sqft', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('service_radius_miles', sa.Float(), nullable=True),
    sa.Column('geometry_json', sa.Text(), nullable=True),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('perimeter_ft', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_sites_id'), 'project_sites', ['id'], unique=False)
    op.create_table('proposal_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('lead_name', sa.String(length=200), nullable=True),
    sa.Column('service_type', sa.String(length=60), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('proposal_amount_low', sa.Float(), nullable=True),
    sa.Column('proposal_amount_high', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('competitor_name', sa.String(length=120), nullable=True),
    sa.Column('competitor_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_outcomes_id'), 'proposal_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_outcomes_lead_id'), 'proposal_outcomes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_proposal_outcomes_tenant_id'), 'proposal_outcomes', ['tenant_id'], unique=False)
    op.create_table('safety_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_site', sa.String(length=300), nullable=False),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=True),
    sa.Column('root_cause', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('osha_recordable', sa.Integer(), nullable=False),
    sa.Column('days_away', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_incidents_id'), 'safety_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_safety_incidents_tenant_id'), 'safety_incidents', ['tenant_id'], unique=False)
    op.create_table('safety_toolbox_talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_site', sa.String(length=300), nullable=False),
    sa.Column('talk_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('foreman', sa.String(length=120), nullable=True),
    sa.Column('crew_count', sa.Integer(), nullable=True),
    sa.Column('signed_off', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_toolbox_talks_id'), 'safety_toolbox_talks', ['id'], unique=False)
    op.create_index(op.f('ix_safety_toolbox_talks_tenant_id'), 'safety_toolbox_talks', ['tenant_id'], unique=False)
    op.create_table('service_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('job_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_type', sa.String(length=60), nullable=True),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('sqft', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('is_qsr', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('warranty_callback', sa.Integer(), nullable=False),
    sa.Column('gc_score', sa.Float(), nullable=True),
    sa.Column('has_photos', sa.Integer(), nullable=False),
    sa.Column('dropbox_url', sa.String(length=500), nullable=True),
    sa.Column('photos_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_history_customer_id'), 'service_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_history_id'), 'service_history', ['id'], unique=False)
    op.create_index(op.f('ix_service_history_tenant_id'), 'service_history', ['tenant_id'], unique=False)
    op.create_table('subcontractor_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=True),
    sa.Column('on_time', sa.Integer(), nullable=False),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('payment_dispute', sa.Integer(), nullable=False),
    sa.Column('rehire_recommended', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractor_performance_id'), 'subcontractor_performance', ['id'], unique=False)
    op.create_index(op.f('ix_subcontractor_performance_subcontractor_id'), 'subcontractor_performance', ['subcontractor_id'], unique=False)
    op.create_index(op.f('ix_subcontractor_performance_tenant_id'), 'subcontractor_performance', ['tenant_id'], unique=False)
    op.create_table('subcontractor_roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bond_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bond_amount', sa.Float(), nullable=True),
    sa.Column('insurance_carrier', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractor_roster_id'), 'subcontractor_roster', ['id'], unique=False)
    op.create_index(op.f('ix_subcontractor_roster_state_code'), 'subcontractor_roster', ['state_code'], unique=False)
    op.create_index(op.f('ix_subcontractor_roster_tenant_id'), 'subcontractor_roster', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=60), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('system_prompt_override', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_tenants_tenant_id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=False)
    op.create_table('truck_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.String(length=30), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed_mph', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('asphalt_temp_f', sa.Float(), nullable=True),
    sa.Column('mix_type', sa.String(length=60), nullable=True),
    sa.Column('plant_departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_delivery_temp_f', sa.Float(), nullable=True),
    sa.Column('estimated_arrival_minutes', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_positions_id'), 'truck_positions', ['id'], unique=False)
    op.create_index(op.f('ix_truck_positions_truck_id'), 'truck_positions', ['truck_id'], unique=True)
    op.create_table('two_factor_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_secrets_id'), 'two_factor_secrets', ['id'], unique=False)
    op.create_index(op.f('ix_two_factor_secrets_user_id'), 'two_factor_secrets', ['user_id'], unique=True)
    op.create_table('workforce_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('member_type', sa.String(length=30), nullable=False),
    sa.Column('trade', sa.String(length=60), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('skill_ratings', sa.Text(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workforce_members_id'), 'workforce_members', ['id'], unique=False)
    op.create_index(op.f('ix_workforce_members_tenant_id'), 'workforce_members', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workforce_members_tenant_id'), table_name='workforce_members')
    op.drop_index(op.f('ix_workforce_members_id'), table_name='workforce_members')
    op.drop_table('workforce_members')
    op.drop_index(op.f('ix_two_factor_secrets_user_id'), table_name='two_factor_secrets')
    op.drop_index(op.f('ix_two_factor_secrets_id'), table_name='two_factor_secrets')
    op.drop_table('two_factor_secrets')
    op.drop_index(op.f('ix_truck_positions_truck_id'), table_name='truck_positions')
    op.drop_index(op.f('ix_truck_positions_id'), table_name='truck_positions')
    op.drop_table('truck_positions')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_subcontractor_roster_tenant_id'), table_name='subcontractor_roster')
    op.drop_index(op.f('ix_subcontractor_roster_state_code'), table_name='subcontractor_roster')
    op.drop_index(op.f('ix_subcontractor_roster_id'), table_name='subcontractor_roster')
    op.drop_table('subcontractor_roster')
    op.drop_index(op.f('ix_subcontractor_performance_tenant_id'), table_name='subcontractor_performance')
    op.drop_index(op.f('ix_subcontractor_performance_subcontractor_id'), table_name='subcontractor_performance')
    op.drop_index(op.f('ix_subcontractor_performance_id'), table_name='subcontractor_performance')
    op.drop_table('subcontractor_performance')
    op.drop_index(op.f('ix_service_history_tenant_id'), table_name='service_history')
    op.drop_index(op.f('ix_service_history_id'), table_name='service_history')
    op.drop_index(op.f('ix_service_history_customer_id'), table_name='service_history')
    op.drop_table('service_history')
    op.drop_index(op.f('ix_safety_toolbox_talks_tenant_id'), table_name='safety_toolbox_talks')
    op.drop_index(op.f('ix_safety_toolbox_talks_id'), table_name='safety_toolbox_talks')
    op.drop_table('safety_toolbox_talks')
    op.drop_index(op.f('ix_safety_incidents_tenant_id'), table_name='safety_incidents')
    op.drop_index(op.f('ix_safety_incidents_id'), table_name='safety_incidents')
    op.drop_table('safety_incidents')
    op.drop_index(op.f('ix_proposal_outcomes_tenant_id'), table_name='proposal_outcomes')
    op.drop_index(op.f('ix_proposal_outcomes_lead_id'), table_name='proposal_outcomes')
    op.drop_index(op.f('ix_proposal_outcomes_id'), table_name='proposal_outcomes')
    op.drop_table('proposal_outcomes')
    op.drop_index(op.f('ix_project_sites_id'), table_name='project_sites')
    op.drop_table('project_sites')
    op.drop_index(op.f('ix_project_retrospectives_tenant_id'), table_name='project_retrospectives')
    op.drop_index(op.f('ix_project_retrospectives_id'), table_name='project_retrospectives')
    op.drop_table('project_retrospectives')
    op.drop_index(op.f('ix_project_metrics_tenant_id'), table_name='project_metrics')
    op.drop_index(op.f('ix_project_metrics_lead_id'), table_name='project_metrics')
    op.drop_index(op.f('ix_project_metrics_id'), table_name='project_metrics')
    op.drop_table('project_metrics')
    op.drop_index(op.f('ix_permit_leads_permit_number'), table_name='permit_leads')
    op.drop_index(op.f('ix_permit_leads_id'), table_name='permit_leads')
    op.drop_table('permit_leads')
    op.drop_index(op.f('ix_payment_transactions_tenant_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_stripe_checkout_session_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_lead_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_page_contents_key'), table_name='page_contents')
    op.drop_index(op.f('ix_page_contents_id'), table_name='page_contents')
    op.drop_table('page_contents')
    op.drop_index(op.f('ix_media_files_tenant_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_lien_calendar_entries_tenant_id'), table_name='lien_calendar_entries')
    op.drop_index(op.f('ix_lien_calendar_entries_state_code'), table_name='lien_calendar_entries')
    op.drop_index(op.f('ix_lien_calendar_entries_id'), table_name='lien_calendar_entries')
    op.drop_table('lien_calendar_entries')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_innovations_tenant_id'), table_name='innovations')
    op.drop_index(op.f('ix_innovations_id'), table_name='innovations')
    op.drop_table('innovations')
    op.drop_index(op.f('ix_human_review_queue_tenant_id'), table_name='human_review_queue')
    op.drop_index(op.f('ix_human_review_queue_id'), table_name='human_review_queue')
    op.drop_table('human_review_queue')
    op.drop_index(op.f('ix_ground_scan_reports_tenant_id'), table_name='ground_scan_reports')
    op.drop_index(op.f('ix_ground_scan_reports_project_site_id'), table_name='ground_scan_reports')
    op.drop_index(op.f('ix_ground_scan_reports_id'), table_name='ground_scan_reports')
    op.drop_table('ground_scan_reports')
    op.drop_index(op.f('ix_grade_logs_tenant_id'), table_name='grade_logs')
    op.drop_index(op.f('ix_grade_logs_id'), table_name='grade_logs')
    op.drop_index(op.f('ix_grade_logs_decision_type'), table_name='grade_logs')
    op.drop_table('grade_logs')
    op.drop_index(op.f('ix_gallery_images_id'), table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_index(op.f('ix_follow_up_tasks_lead_id'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_id'), table_name='follow_up_tasks')
    op.drop_table('follow_up_tasks')
    op.drop_index(op.f('ix_email_logs_recipient_email'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_state_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_contact_messages_tenant_id'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_cashflow_entries_tenant_id'), table_name='cashflow_entries')
    op.drop_index(op.f('ix_cashflow_entries_id'), table_name='cashflow_entries')
    op.drop_table('cashflow_entries')
    op.drop_index(op.f('ix_cashflow_alerts_tenant_id'), table_name='cashflow_alerts')
    op.drop_index(op.f('ix_cashflow_alerts_id'), table_name='cashflow_alerts')
    op.drop_table('cashflow_alerts')
    op.drop_index(op.f('ix_blog_posts_tenant_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_ai_corrections_tenant_id'), table_name='ai_corrections')
    op.drop_index(op.f('ix_ai_corrections_id'), table_name='ai_corrections')
    op.drop_index(op.f('ix_ai_corrections_decision_type'), table_name='ai_corrections')
    op.drop_table('ai_corrections')
    # ### end Alembic commands ###
